name: macOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp*', '**.cmake', '**/CMakeLists.txt' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp*', '**.cmake', '**/CMakeLists.txt' ]
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  main:
    runs-on: 'macos-${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ 11, 12 ]
        build_type: [ Debug, RelWithDebInfo ]
        isPR:
          - ${{ github.event_name == 'pull_request' }}
        exclude:
          - isPR: true
            os: 11
            build_type: RelWithDebInfo
          - isPR: true
            os: 12
            build_type: RelWithDebInfo

    steps:
      - uses: actions/checkout@v3

      - name: Update deps on macOS
        run: |
          # Install oldest compiler that possible
          if [[ "${{ matrix.os }}" == "12" ]]; then
            brew update
            brew install ninja llvm@14 gcc@12
          else
            brew install ninja
          fi

      - name: Configure CMake
        run: |
          if [[ "${{ matrix.os }}" == "12" ]]; then
            compiler_names=(clang gnu apple_clang)
            llvm=/usr/local/opt/llvm@14
            cxx_compilers=("$llvm/bin/clang++" g++-12 clang++)
            stdlib_names=(libcxx libstdcxx default)
            link_options=(
              "-L$llvm/lib;-Wl,-rpath,$llvm/lib"
              "-stdlib=libstdc++"
              ""
            )
            compile_options=(
              "-I$llvm/include;-I$llvm/include/c++/v1/"
              "-stdlib=libstdc++"
              ""
            )
          else
            compiler_names=(apple_clang)
            cxx_compilers=(clang++)
            stdlib_names=(default)
            link_options=("")
            compile_options=("")
          fi

          for (( i=0; i<${#compiler_names[*]}; i+=1 )); do
            for (( j=0; j<${#stdlib_names[*]}; j+=1 )); do
              if [[ "${compiler_names[$i]}" != "clang" && "${stdlib_names[$j]}" != "default" ]]; then
                # TODO(kononovk) I think we should specify path to libstdcxx
                # TODO(kononovk) I dunno how to get GNU GCC to work with other stdlibs
                # TODO(kononovk) I dunno how to get AppleClang to work with other stdlibs
                # Btw I dunno what stdlib would be using libstdcxx or apple_libcxx, just some default
                continue
              fi
              link_option=${link_options[$j]}; compile_option=${compile_options[$j]}                
              if [[ "${compiler_names[$i]}" == "clang" ]]; then
                if [[ "${stdlib_names[$j]}" == "libstdcxx" ]]; then
                  continue  # TODO(kononovk) Specify path to libstdcxx
                fi
                if [[ "${stdlib_names[$j]}" == "default" ]]; then
                  link_option=""; compile_option="-stdlib=libc++"
                fi
              fi

              dir="build_${compiler_names[$i]}_${stdlib_names[$j]}"
              echo $dir
          
              cmake -S . -B $dir                                                                                       \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}                                                            \
                -DIONE_CXX_STANDARD=17                                                                               \
                -DIONE_TEST=SINGLE                                                                                   \
                -DIONE_FLAGS=""                                                                     \
                -DCMAKE_CXX_COMPILER=${cxx_compilers[$i]}                                                              \
                -G"Ninja"                                                                                              \
                -DIONE_LINK_OPTIONS="$link_option"                                                                   \
                -DIONE_COMPILE_OPTIONS="$compile_option"                                                             \
                -DIONE_DEFINITIONS="IONE_CI_SLOWDOWN=8"

            done
          done

      - name: Build
        run: |
          for dir in build*/; do
            echo $dir
            cmake --build $dir --config ${{ matrix.build_type }} --parallel
            echo
          done

      - name: Test
        run: |
          for dir in build*/; do
            cd $dir
            ctest --output-on-failure -C ${{ matrix.build_type }} -V
            cd ..
          done
